// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {container} from '../models';
import {types} from '../models';

export function ContainerPause(arg1:string):Promise<boolean>;

export function ContainerPs():Promise<Array<container.Container>>;

export function ContainerRemove(arg1:string):Promise<boolean>;

export function ContainerRestart(arg1:string):Promise<boolean>;

export function ContainerStart(arg1:string):Promise<boolean>;

export function ContainerStop(arg1:string):Promise<boolean>;

export function ContainerUnpause(arg1:string):Promise<boolean>;

export function ImageLs():Promise<Array<types.ImageSummary>>;
