// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {docker} from '../models';

export function DockerPs():Promise<Array<docker.Container>>;

export function Greet(arg1:string):Promise<string>;
