// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DockerPause(arg1) {
  return window['go']['main']['App']['DockerPause'](arg1);
}

export function DockerPs() {
  return window['go']['main']['App']['DockerPs']();
}

export function DockerStop(arg1) {
  return window['go']['main']['App']['DockerStop'](arg1);
}

export function DockerUnpause(arg1) {
  return window['go']['main']['App']['DockerUnpause'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
