// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ContainerPause(arg1) {
  return window['go']['main']['App']['ContainerPause'](arg1);
}

export function ContainerPs() {
  return window['go']['main']['App']['ContainerPs']();
}

export function ContainerRemove(arg1) {
  return window['go']['main']['App']['ContainerRemove'](arg1);
}

export function ContainerRestart(arg1) {
  return window['go']['main']['App']['ContainerRestart'](arg1);
}

export function ContainerStart(arg1) {
  return window['go']['main']['App']['ContainerStart'](arg1);
}

export function ContainerStop(arg1) {
  return window['go']['main']['App']['ContainerStop'](arg1);
}

export function ContainerUnpause(arg1) {
  return window['go']['main']['App']['ContainerUnpause'](arg1);
}

export function ImageLs() {
  return window['go']['main']['App']['ImageLs']();
}
